# Generated by Django 5.1.3 on 2024-11-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dammage_min', models.IntegerField()),
                ('dammage_max', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('pv', models.IntegerField()),
                ('dodgeChance', models.IntegerField()),
                ('critChance', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
