# Generated by Django 5.1.3 on 2024-11-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_drunk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dammage_min', models.IntegerField()),
                ('dammage_max', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('pv_max', models.IntegerField()),
                ('pv_actuel', models.IntegerField()),
                ('dodgechance', models.IntegerField()),
                ('critchance', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('lvl', models.IntegerField(default=1)),
                ('cash', models.IntegerField(default=0)),
                ('upgradebought', models.JSONField(default=list)),
                ('skinbought', models.JSONField(default=list)),
                ('bestwave', models.IntegerField(default=0)),
            ],
        ),
    ]
