# Generated by Django 5.1.3 on 2024-11-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_drunk', '0002_monster_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Utilisateur',
        ),
    ]
